name = "Glitch"
license = "MIT"
licenselink = "https://github.com/heyvikki/glitch/blob/main/LICENSE"
description = "Lightweight Hugo theme with a focus on content"
homepage = "https://github.com/heyvikki/glitch"
demosite = "https://heyvikki.github.io/glitch/"
tags = ["simple", "minimal", "clean", "fast", "blog", "responsive", "dark mode", "privacy"]
features = ["fast", "blog", "syntax highlighting", "dark mode"]
min_version = "0.41"

[author]
  name = "Lukas Joswiak"
  homepage = "https://heyvikki.pages.dev"
